vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java    
    - vscjava.vscode-java-debug 
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
ports:
- port: 8080
image: gitpod/workspace-mysql
tasks:
  - init: mysql < Reset.sql
